# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/crawled.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/crawled.proto\x12\x07\x63rawler\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n\x08Metadata\x12\x32\n\tcrawledAt\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x0c\n\x04mime\x18\x02 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05title\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04site\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_crawledAtB\x0e\n\x0c_descriptionB\x08\n\x06_titleB\x07\n\x05_site\"|\n\x08\x44ocument\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08\x63hildren\x18\x02 \x03(\t\x12\x10\n\x08original\x18\x03 \x01(\x0c\x12\x11\n\x04text\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x12#\n\x08metadata\x18\x05 \x01(\x0b\x32\x11.crawler.MetadataB\x07\n\x05_textB\tZ\x07/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.crawled_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007/protos'
  _globals['_METADATA']._serialized_start=67
  _globals['_METADATA']._serialized_end=257
  _globals['_DOCUMENT']._serialized_start=259
  _globals['_DOCUMENT']._serialized_end=383
# @@protoc_insertion_point(module_scope)
